name: app-sboard-dev

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy to develop
        uses: appleboy/ssh-action@master
        with:
          username: root
          host: 164.90.218.194
          password: ${{ secrets.DEV_SSH_PASSWORD }}
          script: 'cd /home/forge/app.sboard.su && ./deploy-dev.sh'
